### ISSUE TITLE
Tranfering of tokens between the addresses generated by Eth-lightwallet?

### ISSUE THREAD

**Issue by betheone5** [ConsenSys/eth-lightwallet#129]
Hi,

I have a question and hoping that you could help. I am using eth lightwallet, I have a token contract deployed on my private ethereum. I have created 3 addresses in the HD wallet. Now when i transfer tokens from my coinbase address (totalSupply = 10000), i can see the transaction is mined and token are transfered from coinbase => 1 address in HD wallet. Now as i said, there are 3 addresses in HD wallet, can i transfer tokens from 1 HD wallet address => 2 HD wallet address? in this case, 1 address will be signer? Could you give me any pointer so i can look into? Thanks in advance

/Rakesh

**Comment by christianlundkvist** [comment]
Hi @betheone5, yes you should be able to send tokens from one lightwallet address to another. You'll have to have some Ether in that address. Since lightwallet is a low-level library there is no support for tokens in the library itself, you need to interface with the token contract using web3 and something like the Hooked Web3 provider in the example.
