### ISSUE TITLE
Bitcore dependencies should be updated

### ISSUE THREAD

**Issue by roderik** [ConsenSys/eth-lightwallet#135]
The current version locks fail since today. Fixed versions have been relesed by the bitcore team.

The error is:
<img width="546" alt="screen shot 2017-03-15 at 22 19 15" src="https://cloud.githubusercontent.com/assets/16780/23971423/31e89d6e-09ce-11e7-96ac-8c3593c206a7.png">

Got the same issue in an other project: https://github.com/bitpay/bitcore-ecies/issues/42

In this case, it's the combination with bitcore-mnemonic, a fix release has been made: https://github.com/bitpay/bitcore-mnemonic/releases

**Comment by flyswatter** [comment]
Related to #131

**Comment by christianlundkvist** [comment]
Thanks roderik, will make sure to update in the upcoming release!

**Comment by roderik** [comment]
This can be fixed by merging #136 

The current package.json installs the new v1.2.2 of mnemonic, and does not use the latest 'lib' version, causing the version mismatch.

**Comment by jaycarey** [comment]
We've got the same issue here. We can't build our software at the moment because the current release version of eth-lightwallet pulls in 2 versions of bitcore-lib and triggers the guard above.

@roderik Thanks very much for the fix, we're using that for now.

@christianlundkvist Have you considered freezing the versions you release to npm? Using the carat in dependency versions effectively means the software is mutable in ways your can't control once shipped. This causes problems like the above downstream.

**Comment by christianlundkvist** [comment]
Hi @roderik, I'll merge in your PR today to do a quick fix for this, thanks!

@jaycarey Yeah, you're right in that I should freeze the versions. If everyone followed Semantic versioning these things would not happen, but that's out of my control as your rightly point out.

**Comment by jaycarey** [comment]
@christianlundkvist Agreed, proper versioning is the ideal solution. But I guess I have semver trust issues! 😄 Cheers for the awesome library btw.

**Comment by ajunge** [comment]
Merged version works. I think this issue can be closed

**Comment by christianlundkvist** [comment]
This is now fixed after merging the PR https://github.com/ConsenSys/eth-lightwallet/pull/136 by @roderik
